trigger:
- main
pool:
  vmImage: 'ubuntu-latest'
variables:
  buildConfiguration: 'Release'
  versionMajor: '1'
  versionMinor: '0'
  versionPatch: $[counter(format('{0}.{1}.', variables['versionMajor'], variables['versionMinor']), 0)]
  versionFull: '$(versionMajor).$(versionMinor).$(versionPatch)'


stages:
  - stage: Build
    jobs:
      - job: BuildLibrary
        displayName: 'Build Library'
        continueOnError: false
        workspace:
          clean: all
        steps:
          - task: DotNetCoreCLI@2
            inputs:
              command: build
              projects: './CMCS.Common.WebUtilities/CMCS.Common.WebUtilities.csproj'
              arguments: '--configuration $(BuildConfiguration) /p:Version=$(versionFull)'
          - task: DotNetCoreCLI@2
            displayName: 'dotnet pack $(buildConfiguration)'
            inputs:
                command: pack
                versioningScheme: byEnvVar
                versionEnvVar: versionFull
          - task: NuGetCommand@2
            displayName: 'NuGet push'
            inputs:
              command: push
              nuGetFeedType: external
              publishFeedCredentials: 'Nuget.org'