trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

stages:
  - stage: Build
  jobs:
    - job: BuildLibrary
      displayName: 'Build Library'
      continueOnError: false
      workspace:
        clean: all
      steps:
        - task: DotNetCoreCLI@2
          inputs:
            command: build
            projects: '**/*.sln'
            arguments: '--configuration $(BuildConfiguration) /p:Version=$(Build.BuildNumber)'
        - task: DotNetCoreCLI@2
          displayName: 'dotnet pack $(buildConfiguration)'
          inputs:
              command: pack
              versioningScheme: byPrereleaseNumber
              majorVersion: '$(Major)'
              minorVersion: '$(Minor)'
              patchVersion: '$(rev:.r)'
